:queues:
  - mailers
  - default

:schedule:
  expire_registration_state:
    cron: "0 */15 * * * *"
    class: ExpireRegistrationStateJob
  expire_login_state:
    cron: "0 */15 * * * *"
    class: ExpireLoginStateJob
  expire_ephemeral_state:
    cron: "0 */15 * * * *"
    class: ExpireEphemeralStateJob
