platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: e1ffec0d1940706f157a8c1e0ab8131b7084fa1c
inputs:
  - name: git-main
    path: src
outputs:
  - name: statistics

run:
  path: sh
  args:
    - "-c"
    - |
      curl -H "Authorization: Bearer ${BEARER_TOKEN}" -H 'Accept: application/json' "https://www.${CDN_DOMAIN}/api/v1/report/general?humanize=1" > statistics/output.json
